addSbtPlugin("com.timushev.sbt" % "sbt-updates"          % "0.5.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"              % "1.0.0")
addSbtPlugin("io.spray"         % "sbt-revolver"         % "0.9.1")
addSbtPlugin("io.github.todokr" % "sbt-project-switcher" % "0.1.2")
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
